### ISSUE TITLE
Longitudinal Force x Slip Angle

### ISSUE THREAD

**Issue by czaio11** [teasit/magic-formula-tyre-tool#1]
Hi! My name is Caio and I'm part of a Formula Sae team, here in Brazil and first congratulations for the project and for also making it available for other people to access. A question I had was the following, which curves are really necessary to validate the "fit", my fit was good for FX vs LongSlip, FY vs SlipAngle, FY vs LongSlip. However, the FX vs Slip Angle curve never intersect! Is there any reason for this? Or does this curve not matter to validate the "fit"? The curve I'm referring to is the one below.
![image](https://user-images.githubusercontent.com/98346638/190010809-e217c81f-1b3b-4fa1-aa13-0865892a826f.png)

**Comment by teasit** [comment]
Hello Caio,

I am glad you find the tool useful.

Looking at the scale of your y-axis, you have very little tire force overall. I assume you are looking at data for zero slip ratio, but with slip angle sweeps. You would then expect FX to be almost zero. Instead, try looking at data which has a non-zero slip ratio, if you have such data available for your tire. If those plots also look bad, there might be an issue with your fitted model. 

Cheers,
Tom

**Comment by czaio11** [comment]
Thanks for the answer! I really believe the graph is right, after your considerations, I had forgotten that the slip ratio was equal to zero. When I do 'Slip Angle' x 'Lateral Forces', the graphic is very satisfactory, I believe that Fit is good! It follows two curves, one with longitudinal forces x slip ratio and the other with lateral forces x slp angle. 
![image](https://user-images.githubusercontent.com/98346638/190020575-3557a2f0-f111-4c20-b936-49c0ae94d22b.png)
![image](https://user-images.githubusercontent.com/98346638/190020976-e7e6fd42-d124-4505-a01b-47a51d02d791.png)

**Comment by teasit** [comment]
Great, then I will close this issue. 😄
