### ISSUE TITLE
[BUG] "Downsampling Error for Magic Formula Tyre Tool V1.4"  "Expected X to be nonempty"

### ISSUE THREAD

**Issue by Zaga272** [teasit/magic-formula-tyre-tool#4]
Hey Tom,
I was trying to use the fitter of your Magic Formula Tyre Tool but unfortunately there is a problem with the downsampling. Once i click "Start Fitter" Matlab gives out an error message which says: "Error using downsample, Expected X to be nonempty" I tried it with different FSAE TTC Raw data but the error keeps showing up. So in order to reproduce the error you just have to import Cornering and DriveBrake data of your tyre and start the fitter. I also tried to change the downsampling from 1 to 5 and so on but this did not fix the problem.
I just started learning about Tyre modelling and your tool helps me a lot to understand the tyre characteristics and how to work with the FSAE TTC Data.
So any help to fix this problem would be much appreciated.

Here is also a screenshot of the error message:
![image](https://github.com/teasit/magic-formula-tyre-tool/assets/144263126/c837ee9c-0676-431e-a1af-6cb18a07e52e)

Btw I am using Matlab 2022b

**Comment by teasit** [comment]
@Zaga272 The downsampling factor is not the issue, but that your data did not contain any relevant samples to fit the model to.

The tool currently does not give a better error description, sorry for that. Which dataset are you using?

**Comment by Zaga272** [comment]
Hey, I am using the Raw FSAE TTC Data from Round 9.

**Comment by Gianluca2** [comment]
@Zaga272 You need to run RUN data to make the program work

**Comment by GiridharBhande0z** [comment]
Hi! I've been facing a similar issue. When I try to fit for Mz0, Mx, etc modes, it states me an error that "Parameter 'UNLOADED_RADIUS' is required to fit 'Mz0'". I am not sure what to do, the data cant be incomplete now, can it? Ive tried different measurement data and still face the same issue.

**Comment by teasit** [comment]
Hi,

The issues are not related. In your case, the unloaded tire radius is empty
in your model, which is the default. You then need to set it according to
the tire spec (e.g. 0.2 metres). Search for the name in the table.

Hope that helps
Tom

GiridharBhande0z ***@***.***> schrieb am Mo., 13. Nov. 2023,
19:24:

**Comment by cabadiez** [comment]
I have the same problem as zaga

**Comment by teasit** [comment]
@Zaga272 OK, I can reproduce the issue with some Round 9 data. Will look into it.

**Comment by Zaga272** [comment]
Hey @teasit, now it works. Thank you very much.

**Comment by teasit** [comment]
Alright. Glad to hear it.

Will update the script with the next release!

**Comment by teasit** [comment]
fixed in v1.5.1
