### ISSUE TITLE
[BUG] <Display error in the tire analysis screen>

### ISSUE THREAD

**Issue by malcolm1213** [teasit/magic-formula-tyre-tool#6]
Hey tom,
Thanks for sharing this Magic Formula Tyre Tool, but I'm having a little problem with it now. After I imported the Run FSAE TTC Data from Round 9, the STEADY-STATE SETTINGS part of the Tire Analysis interface is unchanged, and there is no corresponding data in the drop down menu of all options. How can this be resolved please? Or is it a problem with the TTC data I imported?(I am using Matlab 2023b)
Here's a screenshot:
![d979b1a9967de4fd124f80509a90f06](https://github.com/teasit/magic-formula-tyre-tool/assets/154271605/e53b5727-46aa-4822-9fca-e4378b44c265)
![cf5194f7836a2c8c78de13ed08fa439](https://github.com/teasit/magic-formula-tyre-tool/assets/154271605/b24fdc2f-5f31-4163-87e2-242c8e499581)

**Comment by teasit** [comment]
Hi, did the console show any errors or warnings? Which datasets are you using? It has to be RunData in SI units.

**Comment by teasit** [comment]
Also, if you loaded cornering data only you cannot plot FX over SX. Try FY over SA.

**Comment by malcolm1213** [comment]
I see! I did load the cornering data. Yes, no problem after changing FY over SA, thank you very much!
