### ISSUE TITLE
How to download the parser?

### ISSUE THREAD

**Issue by Killian1023** [teasit/magic-formula-tyre-tool#7]
I'm trying to use the Magic Formula Tyre Tool to analyze FSAE TTC data, but I'm having issue when loading importing the data. Which I cannot find the parser to import data. Can you please suggest where I can find the parser to use?

**Comment by teasit** [comment]
Hi, how are you installing and starting the tool?

**Comment by Killian1023** [comment]
I downloaded the tool from matlab file exchange, and open it on my matlab2023b. Is it because I'm using a macbook?

**Comment by teasit** [comment]
Hi,

I haven't tested Mac myself although the SW was developed independent of
OS. Can you manually add the parser to the list?

Tom

Killian ***@***.***> schrieb am Di., 6. Feb. 2024, 09:16:

**Comment by Killian1023** [comment]
Of course, but the issue is I'm not sure where to find the parser, or I have to write my own parser. It would be nice if you can suggest me where to find the parser. Thank you!

Best,
CHEN CHI WEI

**Comment by teasit** [comment]
Hey Kilian,

Either look in your local installation directory of the app or download it from here and try adding it manually:

https://github.com/teasit/magic-formula-tyre-library/blob/aeae697c414c367c9681ef7ce15184221fd46ffb/src/%2Btydex/%2Bparsers/FSAETTC_SI_ISO_Mat.m
