### ISSUE TITLE
[BUG] Fitter failed to solve fit-mode "Mx"

### ISSUE THREAD

**Issue by toxinity10** [teasit/magic-formula-tyre-tool#8]
Hello,

I'm trying to do an aligning moment graph/moment fit mode with cornering data, but when I run the fitter I get this error:

Fitting Mx...
Error using magicformula.v61.Fitter/run
Fitter failed to solve fit-mode "Mx".

Error in MagicFormulaTyreTool/onStartFittingRequested (line 451)
                fitter.run()

Error in MagicFormulaTyreTool>@(varargin)app.onStartFittingRequested(varargin{:}) (line 786)
                'FitterStartRequestedFcn', @app.onStartFittingRequested, ...

Caused by:
    Error using
    magicformula.v61.Fitter/verifyHasMandatoryParameters
    Parameter 'UNLOADED_RADIUS' is required to fit 'Mx'.
 
Error using ui.TyreModelPanel/onFitterStartRequested
Error while evaluating TyreModelPanel FitterStartRequestedFcn.

From my TTC data file, unloaded radius is RUN and when I tried looking for 'UNLOADED_RADIUS' in the fitter I was not able to find it. I was wondering if there was any way to go about this. Thank you.

**Comment by teasit** [comment]
It's a parameter of the model you need to set. It is not determined automatically from the data. Make sure you have no filters set in the table. The search function should also work.

Hope that helps.
Tom
